### ISSUE TITLE
Validate-metadata of your CI tool is getting ran on different files than the ones the PR is trying to merge, leading to failures.

### ISSUE THREAD

**Issue by d-sfounis** [cardano-foundation/cardano-token-registry#1121]
Just saw that the CI validation run got triggered on my PR, but failed. Error logs show that the run was performed in a completely different file than the one my PR was attempting to merge.

You sure your CI tool is validating the correct jsons?

Specifically, my PR (https://github.com/cardano-foundation/cardano-token-registry/pull/1085) is trying to merge `mappings/0aa124d4536745e88208b90821c1bb409b06efc2ec289d71b9df425b534d4152544545.json`

And the CI tool ran `validate-metadata` against my json, which passed just fine, but contines against `./token-metadata-creator validate master/mappings/e14fe3ab348f9a6198359481472601f4557b9f86984f40a186a3b1e8434845525259.json pull-request/mapping /e14fe3ab348f9a6198359481472601f4557b9f86984f40a186a3b1e8434845525259.json` which is totally unrelated to my json, and fails there, causing the entire run to show as failed. Run logs here: https://github.com/cardano-foundation/cardano-token-registry/runs/4803067530?check_suite_focus=true

Maybe something is leaky?

**Comment by AdaTokenizer** [comment]
I'm seeing the same.

**Comment by oz15** [comment]
I believe this happened to my PR as well.

**Comment by BitEdNFP** [comment]
Ours (#1158) failed as well. The reason it says is "description". Is there a character limit, other limitations that are not in the description on the tutorial?

**Comment by d-sfounis** [comment]
> Ours (#1158) failed as well. The reason it says is "description". Is there a character limit, other limitations that are not in the description on the tutorial?

Running `token-metadata-creator validate c76ef5451f551f3c06d48c46b153cb35221b507683b2e413122661b942544544.json` on my machine, resulted in:
```bash
[Error]   [Main.log#290] Failed to validate wallet metadata entry, error was: 'attestation verification failed for: description'.
```

There might be a character limit on your description, it's quite lengthy.
I'd also check if you're using the correct `policy.skey` because the `--logo` tag will happily take 20KB of data, so I can't imagine a description throwing for using 100 words instead of 50!

**Comment by thegalgos** [comment]
Hey, same problem here..., mine is also failing because of another unrelated PR

This is mine
https://github.com/cardano-foundation/cardano-token-registry/pull/1204, **which should run**
```
./token-metadata-creator validate master/mappings/48d67fb303c89ed4297a95af6952a0195326ef4116ce29a10907942747616c676f.json pull-request/mappings/48d67fb303c89ed4297a95af6952a0195326ef4116ce29a10907942747616c676f.json
```

**BUT it is failing because of another file committed by another person!**

```
./token-metadata-creator validate master/mappings/b38d94e35b3e638dce7e5e0b0aeebcbe06987a118b46d3d4c042c8c26861726d6c657373636f696e.json pull-request/mappings/b38d94e35b3e638dce7e5e0b0aeebcbe06987a118b46d3d4c042c8c26861726d6c657373636f696e.json
```

Can someone please take a look? Thanks!

**Comment by sevanspowell** [comment]
I have opened a pull-request to fix this issue: https://github.com/cardano-foundation/cardano-token-registry/pull/1256
