### ISSUE TITLE
Add github labels

### ISSUE THREAD

**Issue by time2devnull** [cardano-foundation/cardano-token-registry#125]
Currently it is fairly simple to navigate through the PRs due to low volume of the opened requests. I imagine, that when the tool becomes poplar, it will be more challenging. 

I suggest adding labels such as 
status: in progress
status: ready for review
status: ready to merge
type: metadata
type: feature
type: bug

etc..

I understand there are other means to reflect the status and type as well as other properties of a PR, but in my experience labels are a lot more visible and functional.

**Comment by time2devnull** [comment]
One more idea, irrelevant to this issue, but still: if it doesn't happen by default yet, I would add check if the `compare` branch has latest changes from `base` (master). This could help avoiding situations when validation check fails because of other mappings (not author's) in the fork, that weren't updated.

**Comment by Godspeed-exe** [comment]
Closing because of old age. Feel free to open new discussions if still relevant.
