### ISSUE TITLE
PTC was added 12 days ago - Token metadata not registered.

### ISSUE THREAD

**Issue by kardall** [cardano-foundation/cardano-token-registry#1472]
So I am wondering how long it takes for this to get processed? cardanoscan still shows it as an unverified policy id.

**Comment by pehcastro** [comment]
Would like to know too :) 3 days here

**Comment by cleanerm5** [comment]
Hi. Could you both please mention the PR numbers and I'll have a look at it asap.

**Comment by kardall** [comment]
Added Pocket Change (PTC) #1193

**Comment by pehcastro** [comment]
BUKZ token #1391

**Comment by cleanerm5** [comment]
If you query the meta API at https://tokens.cardano.org/metadata/007394e3117755fbb0558b93c54ce3bc6c85770920044ade143dc7424506f636b65744368616e6765 or at https://tokens.cardano.org/metadata/4c5d6baa4e94b86ccfba57848f3ed157350e27ec4b2a2e165a7cdc14e2809c42554b5ae2809d the data is retrieved correctly.

Means your json files have been correctly processed and are made available to external services. But I also confirm that the metadata is not listed on cardanoscan or cardanoassets or other explorer-portals. I'll contact some people and hope to sort that out.

**Comment by pehcastro** [comment]
Yeah, it looks right.
Ok, I'll be waiting for a reply.
Thank you very much for your time 👍

**Comment by cleanerm5** [comment]
The problem is related to another issue #1399

Requests to the metadata API currently timeout or take some time to get answered (there seems to be an issue related to DNS) and therefore newer data gets not synced properly even when made available via the registry. We are working on a fix right now. Thanks to @cardanians for their support with this issue.

**Comment by cardanians** [comment]
it looks like you guys have bad name (subjects) - not fault on registry side.

workaround: open cardanoassets.com and find your token, ie.. PTC

http://cardanoassets.com/asset1hy7e2r924yycgwq5fvezkm63c55wzspcz3zhfx

subject is combo policy+encoded name, so in this case
007394e3117755fbb0558b93c54ce3bc6c85770920044ade143dc742+505443

so, if we want get metadata for this token, url is
https://tokens.cardano.org/metadata/007394e3117755fbb0558b93c54ce3bc6c85770920044ade143dc742505443

**Comment by kardall** [comment]
I checked the addition for PTC, and it says:

`"subject": "007394e3117755fbb0558b93c54ce3bc6c85770920044ade143dc7424506f636b65744368616e6765",`

And: https://tokens.cardano.org/metadata/007394e3117755fbb0558b93c54ce3bc6c85770920044ade143dc7424506f636b65744368616e6765

Works.

**Comment by kardall** [comment]
#1567 https://github.com/cardano-foundation/cardano-token-registry/pull/1567

**Comment by pehcastro** [comment]
@cleanerm5  double checked the output on making the .json file and it seems to works ok, not a problem on that side.
also, https://tokens.cardano.org/metadata/4c5d6baa4e94b86ccfba57848f3ed157350e27ec4b2a2e165a7cdc14e2809c42554b5ae2809d
delivers the correct information.

I don't understand what the real problem is or what steps I should take to get the registry working since it is already synced. 
It is a really bad name problem or something on the CTR side? 
Or, if you guys don't know, I should delete my previous PR and create another one (with the same file)?

**Comment by Abremalin** [comment]
So, what should we do?

**Comment by kardall** [comment]
This is getting ridiculous with the lack of responses here. The pull request that was supposedly resolved, was closed, then reopened.
https://github.com/cardano-foundation/cardano-token-registry/pull/1567#event-6053338504

No response from the person that reopened it. And cardanoscan still doesn't list the PTC token as registered.

Please tell us what is up with this, anything that we need to fix I will do. Anything that isn't our fault, please let us know what the heck is going on so that maybe we can assist/help? I don't know at this point.

**Comment by Abremalin** [comment]
@cleanerm5 What can we do to fix this? Please respond.

> 

We did the work around but I was curious if this ever got fixed?

**Comment by hennysch1** [comment]
What workaround?

My project still shows as unverified?

**Comment by Abremalin** [comment]
workaround: open cardanoassets.com and find your token, ie.. PTC

http://cardanoassets.com/asset1hy7e2r924yycgwq5fvezkm63c55wzspcz3zhfx

subject is combo policy+encoded name, so in this case
007394e3117755fbb0558b93c54ce3bc6c85770920044ade143dc742+505443

so, if we want get metadata for this token, url is
https://tokens.cardano.org/metadata/007394e3117755fbb0558b93c54ce3bc6c85770920044ade143dc742505443

**Comment by Abremalin** [comment]
However, being verified here: https://cardanoassets.com/asset1hy7e2r924yycgwq5fvezkm63c55wzspcz3zhfx
Does not solve our problem here. $PTC still shows up as a ? on Minswap.

**Comment by cardanians** [comment]
@Abremalin 

when I want check metadata for PTC:

https://cardanoassets.com/asset1hy7e2r924yycgwq5fvezkm63c55wzspcz3zhfx

it should have this subject if I am right:
007394e3117755fbb0558b93c54ce3bc6c85770920044ade143dc742505443

but you are using:
007394e3117755fbb0558b93c54ce3bc6c85770920044ade143dc7424506f636b65744368616e6765

**Comment by kardall** [comment]
Ya I have to get this signed again.

**Comment by kardall** [comment]
Update for those who have the same issue.

What happened, was I had to use the value on cardanoscan.io for your token in the brackets. So in our Case it shows:

PTC (505443)

So I had to use that instead of "PocketChange" and then do the whole process over again where the subject is:

<PolicyID>505443

So it read as: 007394e3117755fbb0558b93c54ce3bc6c85770920044ade143dc742505443

So if you are still having problems, make SURE that the value you append to the end of the subject policy ID is the correct value, THEN sign it. You can't change it when it's signed as the values don't validate. That was the issue.
