### ISSUE TITLE
ticker greater than 5 chars

### ISSUE THREAD

**Issue by phrankerco** [cardano-foundation/cardano-token-registry#1624]
How is SUNDAE allowed a ticker greater than 5 chars?

Our project would like the same courtesy as it seems it can not be done via any tools or pull requests as it fails validation. 

mappings/e14fe3ab348f9a6198359481472601f4557b9f86984f40a186a3b1e8434845525259.json

We will gladly resubmit if needed. 

Thank you!

**Comment by cleanerm5** [comment]
Hi @phrankerco 

ticker length is no longer limited to 5 characters. See the according [PR](https://github.com/input-output-hk/offchain-metadata-tools/pull/45).

So your procedure would be to update the ticker name in the json file, increment the sequenceNumber by 1 and sign and finalize the file again like described in the [Wiki](https://github.com/cardano-foundation/cardano-token-registry/wiki/How-do-I-update-my-entry-in-the-registry%3F).

Let me know if there are any problems in updating the ticker value.

**Comment by phrankerco** [comment]
I was unaware of the update... thank you for pointing me in the right direction. 

I have a new PR submitted with the ticker included now. Thanks.
