### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by njolegs** [cardano-foundation/cardano-token-registry#1628]
Почему не выставлены метаданные моих участков? Что произошло?

**Comment by cleanerm5** [comment]
Hi @njolegs 

if I read that correctly please let me know which metadata file belongs to you and I can check on that.

**Comment by njolegs** [comment]
https://cnft.io/token/62138a915a57dcef5aabfdc3
Pavia  193 66
           193 65
           192 66
          -173 -160
          -139 -40
I'll be very thankful.
Thanks.

пн, 21 февр. 2022 г. в 19:50, cleanerm5 ***@***.***>:

**Comment by njolegs** [comment]
See what shows me on cardostan

вт, 22 февр. 2022 г. в 07:27, Олег Владимирович ***@***.***>:
