### ISSUE TITLE
Please help to register a token with policy.script and policy.skey missing.

### ISSUE THREAD

**Issue by WhitemanE0** [cardano-foundation/cardano-token-registry#1630]
Dear suppor team, 
Sorry to open it as an issue, but have no other way to contact with you.

On 2021-03-29 I have minted 9,223,372,036,854,776,000 tokens called ATHOM as a part of experiment I described it in the post on Reddit:

https://www.reddit.com/r/CardanoDevelopers/comments/mlbkgg/experiment_of_minting_noticeable_amount_of/

But than I lost policy.script and policy.skey due to hardware failure, so it is doed not exist now anywhere.

From the minting date those tokens went across several hundreds addresses and I would be very happy If I could register them in cardano token registry.

I understant what I'm asking is not the way it should be done, but I believe due to its very early minting date and the attempt to push the native tokens to the limits by total number minted it's a part of Cardano Native Tokens history. And may worth to make an exception.

I can provide whatever possible detailes of my authorship.

Some info:

Policy ID is: 5acc52d5696e52345aec108468050d9d743eb21d6e41305bbc23a27b

Cardanoscan:
https://cardanoscan.io/token/5acc52d5696e52345aec108468050d9d743eb21d6e41305bbc23a27b4154484f4d

My twitter:  https://twitter.com/0xD9E0

http://ne0.xyz/athom/

I'm attaching 5acc52d5696e52345aec108468050d9d743eb21d6e41305bbc23a27b4154484f4d.json.txt without the  "signatures": [] section.

Please kindly review my application.

**Comment by cleanerm5** [comment]
Hey @WhitemanE0 

we'll discuss the options internally and get back to you as soon as we figured out a solution.

**Comment by WhitemanE0** [comment]
I appreciate a lot you even going to discuss this 🙏

**Comment by cleanerm5** [comment]
Hi @WhitemanE0 

after internal discussion we unfortunately cannot help you in this case as there is (at the moment) no cryptographically complete and correct proof possible for the provenance of the token other than using the policy signing keys. Although we see the article and appreciate the work you did, a diversion from the standard based on less "objective" measures then the signature mechanism in place would put us in a situation where our decisions might become prone to censorship, favourism or likewise.

**Comment by WhitemanE0** [comment]
Thank you for your reply.
I understand your conciderations and they valid.

Could you please refuse check-in for ATHOM and accept pool request with CLAW only?
As wiht $CLAW everything is allright.

Thanks and regards,
Vladimir.

**Comment by cleanerm5** [comment]
Hi @WhitemanE0 

I'll close this as the CLAW metadata got merged #1675

**Comment by WhitemanE0** [comment]
Dear Sirs and Madams!
Magically I found my policy script and skey in forgotten backup!
🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 
I celebrate and thanking Universe!
Please accept pull request
https://github.com/cardano-foundation/cardano-token-registry/pull/1751
And know, everything is possible!
