### ISSUE TITLE
is there an official hosted registry somewhere?

### ISSUE THREAD

**Issue by roccomuso** [cardano-foundation/cardano-token-registry#18]
Is this `https://tokens.cardano.org/metadata/` a mirror of this repo?

There's just a few dummy tokens or could be used in a prod environment?

**Comment by gitmachtl** [comment]
the cardano-token-registry is not opened yet (as mentioned in the readme right on the top 😄 )

**Comment by crptmppt** [comment]
closing this issue - registry is open now and queryable (at that endpoint - https://tokens.cardano.org/metadata/) with the live tokens
