### ISSUE TITLE
Token not Verified even after adding to registry 

### ISSUE THREAD

**Issue by hennysch1** [cardano-foundation/cardano-token-registry#1891]
My token was added to registry and merged by @cleanerm5 however it still shows unverified or unregistered everywhere on all DEX's. 

PR was merged a while ago - Foundation Coin (Found) Token Submission https://github.com/cardano-foundation/cardano-token-registry/pull/1801. event-6281720079

https://tokens.cardano.org/metadata/acc223f15f040ae7a355ae84b489aa52a94b77a9a61d73c156514124466f756e64

**Comment by cleanerm5** [comment]
Hi @hennysch1 

the link you posted shows that the metadata is correctly delivered by the metadata server.

Also https://cardanoassets.com/asset1w27rwrvwlq4uq0vektmafnsua7mmj9sz3pk98w shows the metadata correctly for your token.

Also https://cardanoscan.io/token/acc223f15f040ae7a355ae84b489aa52a94b77a9a61d73c156514124466f756e64 looks good.

I can confirm that Muesli lists the token as "unverified": https://ada.muesliswap.com/markets/all/token/acc223f15f040ae7a355ae84b489aa52a94b77a9a61d73c156514124.Found

I'll ask internally if we got contact to the guys maybe they sync the data in another way than CardanoScan or CardanoAssets.

**Comment by cleanerm5** [comment]
Hi again

according to Muesli there is a specific process to do the verification for their platform described here: https://github.com/MuesliSwapTeam/muesliswap-token-verification

Hope this helps.
