### ISSUE TITLE
Duplicate signatures are validated in CI

### ISSUE THREAD

**Issue by admin-cf** [cardano-foundation/cardano-token-registry#197]
Please see an example here. We assume it would be appropriate for CI to fail in this case.
Zendesk ticket has been opened.

https://github.com/cardano-foundation/cardano-token-registry/pull/190

**Comment by sevanspowell** [comment]
Logged an issue in our internal JIRA.

Unfortunately I haven't seen the Zendesk ticket, but may I ask why duplicate signatures are problematic?

**Comment by frog357** [comment]
This continues to be an issue - 2 submissions were blocked in the past 48 hours.
