### ISSUE TITLE
File size and type

### ISSUE THREAD

**Issue by SupremePPC** [cardano-foundation/cardano-token-registry#1991]
I have a request regarding the Cardano Token Register.

Would you add support for the .webp? It is a much lighter file type and allows us to have a higher quality image? Or add support for users to host their image or increase the accepted file size?  

We have an animated image we would like to use, and we have had to reduce our file size. We are currently using an animated png file.

Another great option would be if you were to accept .json files for Lottie Files. Any one of these suggestions would solve our current issue.

Thank you,
Michael

**Comment by cleanerm5** [comment]
Hi Michael

many thanks for the feature request. Adding support for other file types is an option. Putting in links to logo files instead of the binary representation itself is something that from a pure registry perspective is a good thing as it reliefs the registry from storing and serving out the data but impacts the consumers of the registry as they got an additional indirection they need to deal with.

I'll discuss this internally and with the community and implement it once we have a decision.

**Comment by gitmachtl** [comment]
And external Logo link would be possible, currently the signing is done on the base64 encoded part of the included image. Question would be if the signing is than only done on the url to the logo, or on the binary data of the image file that the url is pointing to?

**Comment by cleanerm5** [comment]
Hi @gitmachtl 

I propose that I request a change on CIP-26 to add this feature. If we use an IPFS link or other kind of content-addressable storage then signing the link should be enough (because it is a hash or contains a hash of the actual data).

**Comment by gitmachtl** [comment]
@cleanerm5 ok so than image urls like https://mydomain.com/mycoin.gif would not be an allowed external image url. also, the signing should be able to be made in offline mode, i didn't thought about that. so my thoughs above to use the content on the link are irrelevant.

**Comment by cleanerm5** [comment]
@gitmachtl Yes the proposed solution would exclude urls that are not CAS like IPFS. Alternatively I can add a tag/property for something like externalCASLogo (meaning IPFS or likewise hosted image data) and externalNonCASLogo (like https hosted images). Then the user can choose which tag/property-type to use. When offline signing is needed, the CAS way is the way to go. If offline signing is not needed the user has the freedom to choose.
With regards to the query part: Technically, I can pull the image data from the external source and deliver besides the link also the content or a scaled down preview of the content in the response. The server can also cache the data so there is no latency to fetch the data from IPFS. This is more a question of implementation and perhaps a legal question with regards to copy right infringements if someone links to image data that he actually does not own. But I am not a legal guy and would ask our legal team to check on this.

**Comment by jshear** [comment]
This would be a magnificent improvement to the current implementation. The current 16KB size limit for the token image has led to significant frustration from many projects attempting to register their token. As a solution in the interim, is there any potential for increasing the current 16KB limit? I cannot find the documentation surrounding the 16KB limit justification, but considering the total metadata submission limit is 370KB it seems that storage limitations are not the source of this restriction.

**Comment by Godspeed-exe** [comment]
Hey guys,

I believe this issue in the meanwhile has been fixed and alternatives like CIP68 standard for on chain metadata also solve this.

Feel free to reopen if this is still relevant.
