### ISSUE TITLE
Logo not updating re Pull request Update CAYC logo #1997

### ISSUE THREAD

**Issue by MED2U** [cardano-foundation/cardano-token-registry#1998]
I submitted a pull request to update logo but it is not working, what am i doing wrong?

**Comment by cleanerm5** [comment]
Hi

I guess you refer to https://github.com/cardano-foundation/cardano-token-registry/pull/1997

The final merging of PRs is done manually including a manual review. Usually I'll do those reviews at least once a day. So there might be a max delay of 24h before the merge if there are no problems with the validation.

I merged your PR a minute ago. The registry will serve out the updated data within the next 4 hours.
