### ISSUE TITLE
Adding a sound type on metadata registry 

### ISSUE THREAD

**Issue by DibsGame** [cardano-foundation/cardano-token-registry#2009]
Hi, i want to do a token registry of a asset with some audio included , i have seen others do it but did not find the  how to.

in the token registry we have the logo code but what the code to include audio ? 

here is what i mean: https://pool.pm/2d7444cf9e317a12e3eb72bf424fd2a0c8fbafedf10e20bfdb4ad8ab.CHEDDA

also how to on those descriptons

thanks in advance!

**Comment by cleanerm5** [comment]
Hi @DibsGame 

the data you refer to is not within the token metadata but within the metadata attached to the minting transaction as you can see here: https://cardanoscan.io/transaction/56ea523572a4ca77d618847fd5fb27da3e417109b00183a2695cd9d2b9f2281a?tab=metadata

If you want to include audio with an NFT e.g. you have to link it in the minting transaction the way the link shows.

See e.g. this documentation where they explain how audio files can be "linked" in: https://docs.nft-maker.io/nft-maker-pro/step-by-step-workflow/creating-nfts/configuring-metadata

**Comment by Godspeed-exe** [comment]
Hello @DibsGame 

I believe @cleanerm5 's reply has explained how to attach audio files to NFT's.

Feel free to reopen the issue if you think this is still relevant.
