### ISSUE TITLE
Logo and decimals issue for GLP token

### ISSUE THREAD

**Issue by cryptoproun** [cardano-foundation/cardano-token-registry#2131]
Logo is not appering on pool.pm https://pool.pm/addr1qxslzfvej2zl5gugyfpwj8cy03cwrys2l7qdjekcpz38namq8p06632jjdsahclgjrghjp8aftwzm7dn0j8cvasaruwsyuummv but in the wallet and cardanoscan does, also i change decimals to 6 but i need to change back to 0 , did the same process but validation says the number must be greater than 1 , what should i do please ?

**Comment by cleanerm5** [comment]
Hi @cryptoproun 

regarding the change of the decimals value, just increment the sequenceValue number of the decimals property by 1 meaning as it was 1 at the time of the last commit it must be at least 2 with the next commit.

Regarding the logo being not shown at pool.pm: I can only guess that the logo is maybe to big (600x600px) and that the logos shown on pool.pm for fungible tokens are limited to sizes <= 512x512 pixels. Maybe reach out directly to Smaug from pool.pm
