### ISSUE TITLE
> Hi @hasonhai

### ISSUE THREAD

**Issue by sudapronsirima632** [cardano-foundation/cardano-token-registry#2205]
> Hi @hasonhai
> 
> the validation failed because you did not increment the sequenceNumber of the updated properties. Please increment the sequenceNumber of the updated properties by 1 and sign the metadata again (because the sequenceNumber is also included in the signing process).

Thank you. I have just resubmitted the new one.

_Originally posted by @hasonhai in https://github.com/cardano-foundation/cardano-token-registry/issues/2201#issuecomment-1172680862_

**Comment by cleanerm5** [comment]
Hi @sudapronsirima632 

the validation worked for those changes and I already merged the PR.
