### ISSUE TITLE
Broken link in Wiki - token name and ticker

### ISSUE THREAD

**Issue by fill-the-fill** [cardano-foundation/cardano-token-registry#2446]
There is a broken link to Cardano docs in [Is my token name and ticker unique in the registry ?](https://github.com/cardano-foundation/cardano-token-registry/wiki/Is-my-token-name-and-ticker-unique-in-the-registry-%3F) to developer guide on Native Assets.

**Comment by cleanerm5** [comment]
I fixed it. Thanks for the hint!
