### ISSUE TITLE
Hey, Just new... How can I register my token ?

### ISSUE THREAD

**Issue by GabrielTexier23071997** [cardano-foundation/cardano-token-registry#249]
Hi I didn't understand everything on how to register my 894212cbfc91f506fd273a9814625c425477790a35bda34e13a1c167 Token TAX (I also have a logo), but i don't know what I have to fill out (?) The Json application. 
Can someone help me ?

Thanks
Gab

**Comment by TrumpFanPool** [comment]
> 
> 
> Hi I didn't understand everything on how to register my 894212cbfc91f506fd273a9814625c425477790a35bda34e13a1c167 Token TAX (I also have a logo), but i don't know what I have to fill out (?) The Json application.
> Can someone help me ?
> 
> Thanks
> Gab

Hi, have you seen https://github.com/cardano-foundation/cardano-token-registry/wiki ?

**Comment by GabrielTexier23071997** [comment]
Thanks
