### ISSUE TITLE
Testnet launch upcoming! Need to merge PR

### ISSUE THREAD

**Issue by carleryd** [cardano-foundation/cardano-token-registry#2490]
Apologies for creating an issue on top of a PR, but [our public testnet starts on Tuesday](https://medium.com/@GeniusXOfficial/the-genius-x-launchpad-testnet-announced-8620aefcbfdf) and we could really need a review on our entry before then!

Please see open PR: https://github.com/cardano-foundation/cardano-token-registry/pull/2487

Thank you!!

**Comment by cleanerm5** [comment]
Has been merged https://github.com/cardano-foundation/cardano-token-registry/pull/2487
