### ISSUE TITLE
Token decimals

### ISSUE THREAD

**Issue by anhdungle93** [cardano-foundation/cardano-token-registry#25]
How can I specify the number of decimal number of our tokens? I don't see any such field in the registry entries.

**Comment by gitmachtl** [comment]
Its not possible to specify decimals for tokens via the token-registry.

**Comment by anhdungle93** [comment]
How can one define the token decimals on Cardano, if not through token-registry?

**Comment by gitmachtl** [comment]
Currently its not possible to define decimals on native assets at all.
