### ISSUE TITLE
Locating a $handle

### ISSUE THREAD

**Issue by Abram570** [cardano-foundation/cardano-token-registry#2550]
I minted the handle $pistolvania , when i was fairly new! I did this with the Nexo "wallet" not knowing they didn't hold nft ! So now im trying to figure out if i can somehow retrieve it and have it sent to my eternl somehow!???

**Comment by cleanerm5** [comment]
Hi. actually you can use the same wallet in Eternl, all you need to do is recover it from your seed phrase of the Nexo wallet.

Otherwise, find the NFT in your old wallet that represents the handle and send it like every other NFT to your new wallet.

https://pool.pm/$pistolvania

**Comment by Abram570** [comment]
Lemme give it a shot. Much appreciated!

**Comment by cleanerm5** [comment]
I'll close this as it is not really related to the token registry itself. But feel free to reach out to me via Telegram (@cleanerm5) if you need further support.

**Comment by Abram570** [comment]
Again i appreciate it  im still figuring things out here.
