### ISSUE TITLE
How do you perform the Human vetting process ?

### ISSUE THREAD

**Issue by nhenin** [cardano-foundation/cardano-token-registry#261]
Hi,  I have been reading the following in your doc : 
`Submissions will be subject to automated checking for well-formedness and human vetting before being merged to the registry.` 

How do you perform the human vetting ?

Thanks :-)

**Comment by Godspeed-exe** [comment]
Hello @nhenin 

Sorry for the (very) late reply. This means that actual humans are performing checks on respecting the terms and conditions.
I'll close this issue, feel free to reopen to continue the conversation.
