### ISSUE TITLE
Invalid json document for token 203ad638c94f36bd603c7ae3d3d53e7e742396185d6dc4fb9df3b2425155414e544943

### ISSUE THREAD

**Issue by johnnuy** [cardano-foundation/cardano-token-registry#2672]
Duplicate key "subject" at 1359 [character 14 line 33]

**Comment by cleanerm5** [comment]
Hi @johnnuy 

thanks for pointing this out. Actually duplicate keys in JSON docs do not seem to be forbidden according to the standard (standard here: https://www.ecma-international.org/publications-and-standards/standards/ecma-404/. explanation here https://stackoverflow.com/questions/21832701/does-json-syntax-allow-duplicate-keys-in-an-object)

However. Good catch. Let me check if I can get rid of the duplicate key without harming the integrity/validity of the entry itself.

**Comment by johnnuy** [comment]
Yeah must be just the library i'm using to parse the data, that is enforcing the unique keys.

**Comment by cleanerm5** [comment]
Fixed it with PR #2674

**Comment by cleanerm5** [comment]
I merged a version without the duplicate key. The file remains valid, so no change as seen from the consumer side. Thanks again.
