### ISSUE TITLE
Failed to validate metadata - rate limit exceeded?

### ISSUE THREAD

**Issue by viraladmin** [cardano-foundation/cardano-token-registry#2731]
My token submission was rejected and the only error it shows it "rate limit exceeded" with an IP I have no clue about.

I have no idea what this error is or means really.

https://github.com/cardano-foundation/cardano-token-registry/actions/runs/4196307722/jobs/7277100199 

help?

**Comment by viraladmin** [comment]
@cleanerm5 any chance you have any suggestions here?

**Comment by cleanerm5** [comment]
Hi @viraladmin 

I triggered the validation again and it succeeded. Your PR has been merged. Sorry for the inconvenience.
