### ISSUE TITLE
Problem witn NAME between our token (ROUND) and cEUR

### ISSUE THREAD

**Issue by RoundTripToken** [cardano-foundation/cardano-token-registry#2772]
Hi,
we have a problem with tag NAME between our token, called ROUND (policyID:3682715f97086e72ff37a7e6759a5ff0b44c98296afc2b407debe52b) and the token called cEUR (policyID: c0267e374e0368fdc831d180d7b3a36fd07cbd94fdd837e347098875).

As you can see in CardanoScan and in the json file submitted here (cardano-token-registry), cEUR is using 'ROUNDTRIP' as value in the tag Name, as our token.

This is our token------ as you can see that we have submitted json file on 2023/02/10 and our token was minted on 2023/02/08 (check Cardanoscan)
ROUND - Token
https://github.com/cardano-foundation/cardano-token-registry/pull/2724/
ROUND RoundTrip Token submission #2724
@[RoundTripToken](https://github.com/RoundTripToken/cardano-token-registry/commits?author=RoundTripToken)
RoundTripToken committed on Feb 10
    "name": {
        "sequenceNumber": 0,
        "value": "ROUNDTRIP",
        "signatures": [
            {
                "signature": "2ac37051824f2f637960976cfada9f760d71f3dba85a2e5b8a30bf30fcc25ed119bc51551b0220cd1ccdf10624cb23b4adc24b20d900d4fe4870db3ea5715a03",
                "publicKey": "5817526d712f71e33a31ac3429fb7ce70b3e17e727044d9a2a51493e7894ba48"
            }
        ]
    },

This is the other token ---- as you can see creators have submitted json file on 2023/02/15 and this token was minted on 2023/02/12 (check Cardanoscan)
cEUR - token
https://github.com/cardano-foundation/cardano-token-registry/pull/2759/
cEUR Token submission #2759
[cEURToken](https://github.com/cEURToken/cardano-token-registry/commits?author=cEURToken) committed on Feb 15
"name": {
        "sequenceNumber": 0,
        "value": "ROUNDTRIP",
        "signatures": [
            {
                "signature": "7dceffebd99e4e404b87d2e55d19254d1c18220485b09e6e39a6663beca478a157f67c2c370d4fee269aeba45a3bccec856f1522332eef7216a4ec4708748d04",
                "publicKey": "5817526d712f71e33a31ac3429fb7ce70b3e17e727044d9a2a51493e7894ba48"
            }
        ]
    },

So, what i'm asking for is to avoid cEUR token to use 'ROUNDTRIP' as value in tag 'Name' because we are using same in our token 'ROUND' and our token was created first and submitted first the metadata to cardano-token-registry.
Also, if you check the URL of cEUR token (https://www.ceurtoken.com/) they don't have any relationship with 'ROUNDTRIP' or any mention to this name/concept.

Our token (ROUND) is also verified in Minswap and now we have some problems with users that try to search us but find cEUR token due the tag Name.

Please take in consideration this issue and try to solve this situation to avoid problems with end users or scams.
Thanks!

**Comment by cleanerm5** [comment]
Hi @RoundTripToken 

The NAME for the ceurtoken was changed by their team 3 days ago.

https://github.com/cardano-foundation/cardano-token-registry/blob/master/mappings/c0267e374e0368fdc831d180d7b3a36fd07cbd94fdd837e34709887563455552.json

I hope this solves the issue?

**Comment by RoundTripToken** [comment]
Yes!
Thanks!!!!
