### ISSUE TITLE
encoding of PolicyID

### ISSUE THREAD

**Issue by anhdungle93** [cardano-foundation/cardano-token-registry#29]
In the readme.md of the repo the field subject is created like this "The base16-encoded policyId + base16-encoded assetName". But according to these instructions https://input-output-hk.github.io/offchain-metadata-tools/#submitting-your-first-metadata-entry the policy id is not encoded. Which one is correct?

**Comment by gitmachtl** [comment]
the policyID itself is already in hex(base16) format, so no additional encoding needed. the assetName ByteArray must be encoded into a hex-string(base16) yes.

**Comment by anhdungle93** [comment]
> the policyID itself is already in hex(base16) format, so no additional encoding needed. the assetName ByteArray must be encoded into a hex-string(base16) yes.

thanks, makes sense. Can you explain what `basenc --base16` does because when I applied to policy id `POLICY_ENC=$(echo $POLICY_ID | basenc --base16 | awk '{print tolower($0)}')` it gives me something different than original id.

**Comment by gitmachtl** [comment]
basenc --base is encoding an input string into a hex string. but i use the tool xxd for that. but don't encode the policy_id again. only encode the assetName.

**Comment by anhdungle93** [comment]
that's why I am asking, since policy id is already in hex format, then basenc --base16 should not change the string, no?

**Comment by gitmachtl** [comment]
it interprets the string as ascii itself, so of course it would change it. you can run it over and over again.

**Comment by milosmns** [comment]
That description is absolutely unclear. `+` can mean 10 different things.

The only link where I could find any useful information should have been copy pasted in the README (or the samples at least) — [Submitting your first metadata entry](https://input-output-hk.github.io/offchain-metadata-tools/#submitting-your-first-metadata-entry).

**Comment by gitmachtl** [comment]
You can make a PR to update the description to bring in a concat for that.
