### ISSUE TITLE
Unknown rate limit

### ISSUE THREAD

**Issue by refi93** [cardano-foundation/cardano-token-registry#291]
I was checking the terms and conditions https://github.com/cardano-foundation/cardano-token-registry/blob/master/API_Terms_of_Use.md which suggests there are some limits to exceed, but I didn't find anywhere the exact figure - could you please clarify what is the exact rate limit/fair usage policy of the service?

**Comment by refi93** [comment]
Ok, I just found it while checking out offchain-metadata-tools docs: https://input-output-hk.github.io/offchain-metadata-tools/#build-the-project-from-source and it's apparently hosted at https://metadata.cardano-testnet.iohkdev.io

**Comment by Godspeed-exe** [comment]
Hello @refi93 

I know it's been a very long time, but in the meantime this backend has changed quite a bit. The current rate limits are set to:
- 100 requests per IP in 5 minutes
- no requests bigger then 3 mb
- no requests other then to 'metadata/' endpoint

Let me know if you have any questions!
