### ISSUE TITLE
How to obtain data to add a logo after registration

### ISSUE THREAD

**Issue by capitalismtoken** [cardano-foundation/cardano-token-registry#3231]
Hello. First of all, a warm greeting to whoever reads this, I hope you are well. Please, I need help to add a logo to my token. My token has already been registered, but for verification I need to add a logo. I know that the code should follow the following structure:
"policy": "",
     "logo": {
        "sequenceNumber": 1,
        "value": "",
        "signatures": [
            {
                "signature": "",
                "publicKey": ""

Now the problem is that I don't know where to get the signature and publicKey from. I think the link to the image goes in value, but in a different format that I don't know how to get either.

I've seen about the token-metadata-creator, but I can't find how to run or use it to generate the data I want.

Could someone please help me? I will appreciate a lot

Hugs :)

**Comment by cleanerm5** [comment]
Hi @capitalismtoken 
Can you please point me to the metadata file that already has been registered? How did you actually create this first version (which should basically already contain the public key information you are looking for).

**Comment by capitalismtoken** [comment]
Thanks @cleanerm5  for your answer. 
1. The file with metadata that they asked me to modify is the registry file, which is called6a659a86a0f35825bb9b0724ee70bc6a090e5910e1423a86a48cc955434150.json
2. I created the token through the website https://cardano-native-token.com/ . 

Since the morning I'm trying to learn how to use Nix, to use the metadata creator token and I have 25 Chrome tabs open just to install Ubuntu. I go one step forward and I get 1 error LOL

**Comment by cleanerm5** [comment]
Hey @capitalismtoken 

If you minted the token via this website I assume you do not own the private key that was used for the minting operation? We had those kinds of cases in the past already and the best way forward was contacting the website owners and asking for support and they usually were able to help people out.

If you have the private key of the minting policy, let me know and we can try to figure out a way to get this running on your local machine but yes...Linux is a prerequisite.

**Comment by capitalismtoken** [comment]
Hi @cleanerm5
Thank you very much for your answer. Indeed, you were right. I solved it with the website. Thanks for your help. I already made a PR to record the changes in the registration json.

A big hug, I wish you a nice week
