### ISSUE TITLE
Logo not loading

### ISSUE THREAD

**Issue by mufasa2531** [cardano-foundation/cardano-token-registry#3239]
Hello good day!

We're having an issue.. 

According to Minswap, the logo should appear on their DEX after the PR has been merged.

![image](https://github.com/cardano-foundation/cardano-token-registry/assets/135310611/d6034fc2-d5a2-4efa-829e-8b2dbf88e1aa)

Our PR has been merged 17hrs ago. https://github.com/cardano-foundation/cardano-token-registry/pull/3229

We may ask if there's something went wrong on our side?

We used 49kb PNG file. filename(hydragamesLogo2.png)

![hydragamesLogo2](https://github.com/cardano-foundation/cardano-token-registry/assets/135310611/d6e1a417-8d0e-43ed-8d3f-6c27da3f7e13)

With this command using offchain-metadata-tool

token-metadata-creator entry 43a078846ae28140f5a5c2714ffcc689555d7e0efcfcaf79ce2910fa487964726147616d6573 \
  --ticker "HYDRGMS" \
  --url "https://hydragames.xyz/" \
  --logo "hydragamesLogo2.png" \
  --decimals 0   

Thank you!

**Comment by mufasa2531** [comment]
Hello @cleanerm5 thank you for your reply, I PR the new metadata entry here:
https://github.com/cardano-foundation/cardano-token-registry/pull/3279/files

Question: Does the new metadata won't conflict on my old PR that's already merged? because both has the same details, except signatures and filename.

Thanks!

**Comment by cleanerm5** [comment]
Hi @mufasa2531 

it does not conflict. You can delete the old metadata following the instructions provided in the [Wiki](https://github.com/cardano-foundation/cardano-token-registry/wiki/How-do-I-delete-my-entry-from-the-registry%3F) but is not mandatory.
