### ISSUE TITLE
Assert subject is lowercase

### ISSUE THREAD

**Issue by cardano-tools-nft** [cardano-foundation/cardano-token-registry#353]
I registered the subject

33aeeac38bbc7776c6e2c4787b24e99ffe8a17fb6829456492040d2856697661466964656C
but it is not recognized by dirrefent tools, because the base16 part of the toke name was not lowercase.

I recommmend to extend the automatic check, that the subject is all lowercase.

**Comment by gitmachtl** [comment]
you have to use lowercase for the whole string. just resubmit another registration with all lowercase.
