### ISSUE TITLE
Service https://tokens.cardano.org/metadata/query returns 429 Too Many Requests

### ISSUE THREAD

**Issue by dariusdev** [cardano-foundation/cardano-token-registry#3575]
Hi, 
i tried to use https://tokens.cardano.org/metadata/query and each time i receive response 429 Too Many Requests
something is wrong with  throttling there, because cant send even 1 req / per minute without receivint that error

**Comment by erikmaide** [comment]
Previoulsy it could handle the load of requests, are there news about it?

**Comment by Godspeed-exe** [comment]
Hello @dariusdev  and @erikmaide 

I know it's been a while, but in the meantime this backend has changed quite a bit. The current rate limits are set to:
- 100 requests per IP in 5 minutes
- no requests bigger then 3 mb
- no requests other then to 'metadata/' endpoint

Let me know if you have any questions!
