### ISSUE TITLE
Is it possible to create PR programmatically?

### ISSUE THREAD

**Issue by adakondacoin** [cardano-foundation/cardano-token-registry#3693]
Hi, 
i wrote some code to mint a token and create the entry json.
i tried creating a simple PR from my fork to the cardano-token-registry programmatically and it tells me i don't have permission.

Do you know if this is only an issue with the api  token? 
Thanks in advance

**Comment by Godspeed-exe** [comment]
Hello @adakondacoin 

It's been a while since I heard back about this, so I'm closing this issue. 

Let me know if you have any questions!
Happy holidays!
