### ISSUE TITLE
Invalid PNG file, signature broken

### ISSUE THREAD

**Issue by anhdungle93** [cardano-foundation/cardano-token-registry#37]
I want to add the optional field logo but got this error `Loading image data: Error in $: Verifying PNG: Invalid PNG file, signature broken`. Do you know what may cause this?

**Comment by gitmachtl** [comment]
Make sure that you use the correct path to the PNG file on your system, also make sure that the file is a valid PNG Image file, and also that it is max. 64kB in size. If you have a complex path, but it into quotes ""

**Comment by anhdungle93** [comment]
I used a different png file and it worked.
