### ISSUE TITLE
Token register with an existing policy id

### ISSUE THREAD

**Issue by Mandolab** [cardano-foundation/cardano-token-registry#3731]
Hi;
I would like to register a token that is already created and with an existing policy ID.
How to do it?.
Thanks

**Comment by Godspeed-exe** [comment]
Hello @Mandolab 

If you are the holder of the policy.skey then you'll be able:
- fork this repo
- generate the files for your submission which can be done through the tools listed on the README of the repo
- add your files into the /mappings folder
- create a pull request for your changes on this repo
- we'll review it and if all is correct we'll merge it

But you have to be the holder of the policy.skey to generate the file with the required signatures.

Feel free to let us know if you have any questions!

**Comment by Mandolab** [comment]
[972d64b3d791c6ec40b8280a96ee968607b7c036f5028da30f2c53814c4547414359.json](https://github.com/cardano-foundation/cardano-token-registry/files/13686682/972d64b3d791c6ec40b8280a96ee968607b7c036f5028da30f2c53814c4547414359.json)

**Comment by Godspeed-exe** [comment]
You have to follow the above steps to get it included though. Just pasting it here doesn’t work.

**Comment by Godspeed-exe** [comment]
Hello @Mandolab 

Since I haven't heard back I'm closing this issue, but feel free to submit your token request through the above described process.

Happy holidays!
