### ISSUE TITLE
Hi Godspeed-exe, you're quite right. My mistake, could you change this to the right decimal so that 8,000,000,000 token are created. So I know in future, is this a decimal of 1 that should be used?

### ISSUE THREAD

**Issue by LondonPass2024** [cardano-foundation/cardano-token-registry#3805]
Hi Godspeed-exe, you're quite right. My mistake, could you change this to the right decimal so that 8,000,000,000 token are created. So I know in future, is this a decimal of 1 that should be used?

_Originally posted by @LondonPass2024 in https://github.com/cardano-foundation/cardano-token-registry/issues/3801#issuecomment-1873848248_

**Comment by Godspeed-exe** [comment]
This "issue" is related to an existing pull request, shouldn't need an actual issue.
