### ISSUE TITLE
Help with Minswap Pool

### ISSUE THREAD

**Issue by LondonPass2024** [cardano-foundation/cardano-token-registry#3807]
Thanks for your help in the Pull Request. I since created a Liquidity Pool on Minswap to list my token for sale (first time). Token:  c6866e99d228e1c6a1ce276ddc1f7f379a4bcc90d2e6a8994181cdf8
But I cannot search for it on Minswap, and the icon shows as a '?' 

Is there anything I need to do to resolve this and also have it listed on CoinMarletCap with a market cap size? 

Is this the right way to sell my token?

![image](https://github.com/cardano-foundation/cardano-token-registry/assets/155310722/7896537e-4285-475b-858a-f2c08f562062)

**Comment by Godspeed-exe** [comment]
Hello @LondonPass2024 

that’s sadly something we can not answer, I would redirect you to MinSwap and CoinMarketCap teams for those questions.

**Comment by LondonPass2024** [comment]
ok, thank you for the support thus far. youve been excellent
