### ISSUE TITLE
How do i create a logo as a byte string

### ISSUE THREAD

**Issue by LondonPass2024** [cardano-foundation/cardano-token-registry#3809]
Hi There
How do i create a logo as a byte string? I am trying to following this article to verify my token on minswap but dont know how to convert an image (attached) to a byte strong.  https://github.com/cardano-foundation/cardano-token-registry

Many thanks
Sam
![Baby Shib Moon Program](https://github.com/cardano-foundation/cardano-token-registry/assets/155310722/38819e81-d0b0-49b7-acc6-2d5b79fa1e0b)
![Baby Shib Moon Program](https://github.com/cardano-foundation/cardano-token-registry/assets/155310722/ea176d2a-b699-47da-ae95-d19b4664d4e5)

**Comment by adakondacoin** [comment]
Hey bud, you have to use a base64 format:

https://www.base64-image.de/

**Comment by Godspeed-exe** [comment]
Thanks for helping out @adakondacoin ! :raised_hands: :muscle:

**Comment by LondonPass2024** [comment]
Thank you both! :)

**Comment by LondonPass2024** [comment]
BTW, any idea of turnaround times for the team reviewing this pull request: 
Being the first time creating, registering and now verifying a token, I'm wondering if there's something I've missed for the above pull request to be successfully approved (e.g. know they need an icon and think this was done as part of the token creation process but i'm not entirely sure how to verify an icon does exist).

**Comment by Godspeed-exe** [comment]
Hello @LondonPass2024 

Cardano Foundation is not related to MinSwap and their processes, so anything we say would be complete speculation. I would look at older pull requests and compare / calculate an average. Make sure that your submission is complete & correct. 

For any other MinSwap questions I would refer you to their support channels.

**Comment by LondonPass2024** [comment]
Ok, thanks Godspeed-exe
