### ISSUE TITLE
Hi Godspeed, so i created a new JSON file with the right logo and signature but i received a metadata validation failure. Did I do something wrong?

### ISSUE THREAD

**Issue by LondonPass2024** [cardano-foundation/cardano-token-registry#3820]
Hi Godspeed, so i created a new JSON file with the right logo and signature but i received a metadata validation failure. Did I do something wrong?

_Originally posted by @LondonPass2024 in https://github.com/cardano-foundation/cardano-token-registry/issues/3819#issuecomment-1877104058_

**Comment by Godspeed-exe** [comment]
Please don't make separate issues :sweat_smile: We follow it up in the pull request... thanks!

**Comment by LondonPass2024** [comment]
Sorry
