### ISSUE TITLE
policy ID registry

### ISSUE THREAD

**Issue by cerraio** [cardano-foundation/cardano-token-registry#3894]
FEATURE REQUEST:
currently there is no way to register policy ID, only policy ID and token name combination.
because of this, projects like Minswap need to add thousands of different tokens constantly:
https://github.com/cardano-foundation/cardano-token-registry/commit/8e5f3dc14348229b54c7285077044be58783e247

Our protocol works in the same manner. we mint unique NFT, which represents user loan ownership, meaning for each new loan we mint a unique NFT (same policy ID, different token name).

Currently there is no means to add metadata to these tokens, except from constantly manually adding each and every token to this repo.

It would be extremely beneficial to the community, if there would be a possibility to add metadata to the policy ID itself, or a structure to describe metadata for ANY token of that policy ID, for example, using wildcard symbol instead of token name

**Comment by Godspeed-exe** [comment]
Hello @cerraio 

Thanks for reaching out, the point is definitely open for an improvement. The community has already created CIP68, with a specific implementation for Rich FT (adding all the data from the token registry on chain). This standard is still fairly new and not many DEX's have support for this. 

For changing these standards I would advise you to go through the CIP process.
