### ISSUE TITLE
Pls check why got failed again!

### ISSUE THREAD

**Issue by billpi1** [cardano-foundation/cardano-token-registry#3973]
https://github.com/billpi1/cardano-token-registry/edit/master/mappings/4f2a93e7e89d2db75ade14859a0002a8debb25b877145099c32b6ed455454641.json?pr=%2Fcardano-foundation%2Fcardano-token-registry%2Fpull%2F3972

**Comment by Godspeed-exe** [comment]
I don’t this was meant as an “issue”?
