### ISSUE TITLE
Old mapping (requested to be removed) still present in mappings/

### ISSUE THREAD

**Issue by Zsargul** [cardano-foundation/cardano-token-registry#4034]
A couple days ago I requested to [remove my old mapping](https://github.com/cardano-foundation/cardano-token-registry/pull/4019#event-11717255183) as I was using a new policy ID (My initial script used for minting was incorrect). I changed the name and description fields to VOID and the PR was accepted and merged as can be seen on the PR page. However in the repo the mapping `a0993dac66bc9b79b730b767789d36eb7a053192a3a7b6c2ffef6bc1546f594149.json` is still present with it's logo and some other metadata. This makes 2 almost identical tokens show up on the blockchain explorer and might be causing some confusion. Did I overlook something during the process of trying to get my metadata removed?

As you can see [here](https://cardanoscan.io/token/a0993dac66bc9b79b730b767789d36eb7a053192a3a7b6c2ffef6bc1546f594149) the old metadata still shows up on cscan.

**Comment by Godspeed-exe** [comment]
Hey @Zsargul 

I think it's because this file from the last pull request was deleted. Can you pull this again? I'll merge it asap!

Thanks

cc: @VladislavKudrin

**Comment by Godspeed-exe** [comment]
After further investigation it seems like the API was updated with the VOID values, so it should be effective. I've reached out to Cardanoscan team to verify on their side. Thanks for the notification!

**Comment by Zsargul** [comment]
Thanks! It seems that [the specific PR to remove the file](https://github.com/cardano-foundation/cardano-token-registry/pull/4025) was closed rather than merged. Maybe this is related?

**Comment by Zsargul** [comment]
The blockchain explorer has updated. It seems that it displays (or rather doesn't) the metadata properly now.

**Comment by Godspeed-exe** [comment]
Hello @Zsargul 

I've completed @VladislavKudrin 's PR to delete the mapping, so this should as of now (or in the coming hours) reflect correctly across all the platforms once they refresh from the token registry.

Sorry for the inconvenience!
