### ISSUE TITLE
Help with a Registry Pull Request

### ISSUE THREAD

**Issue by LondonPass2024** [cardano-foundation/cardano-token-registry#4235]
Hi there, I cant seem to upload my file to the Mappings folder. Would you be able to help me with the creation of a Pull Request for updating the cardano registry with the attached json? 
[167e986f21756eb7b7588c8753500ad5ecfabcadccd176061c67346e504550455a.json](https://github.com/cardano-foundation/cardano-token-registry/files/14608113/167e986f21756eb7b7588c8753500ad5ecfabcadccd176061c67346e504550455a.json)

**Comment by LondonPass2024** [comment]
i couldnt seem to upload a file but think i managed using the other option. Please see if this is correct: https://github.com/cardano-foundation/cardano-token-registry/pull/4236

**Comment by VladislavKudrin** [comment]
Hi @LondonPass2024,

can this be closed?

**Comment by LondonPass2024** [comment]
Thanks for your help Vladislav. It sure can be closed.
