### ISSUE TITLE
incorrect pull request 4232

### ISSUE THREAD

**Issue by pepauge** [cardano-foundation/cardano-token-registry#4242]
Sorry VladislavKudrin. 4232 was not the correct pull request. This request was revised by Kartiiyer12 and tell me that 10 decimals isn't a good idea. The correct request is 4234. The json is the same but with 0 decimals. Can anyone revert 4232 and pull 4234, please?

**Comment by VladislavKudrin** [comment]
Hi @pepauge,

you can update decimals following this guide [How do i update my entry](https://github.com/cardano-foundation/cardano-token-registry/wiki/How-do-I-update-my-entry-in-the-registry%3F)

Feel free to ask any questions.

**Comment by pepauge** [comment]
thanks a lot!
