### ISSUE TITLE
Deceptive site ahead https://cardano-stake-pool-cologne.com/ SPCOL Token 

### ISSUE THREAD

**Issue by SPOOLCOLOGNE** [cardano-foundation/cardano-token-registry#4305]
My website has been flagged as deceptive. To remove this restriction, please verify my token registration again: SPCOL Token. Policy Id: 5695e476953cd3f9a7f77c10f879112b070e8ec65cc171d29cef8ca9

On the homepage of my website, I have prominently displayed the following information: 

SPCOL Token. 
Policy Id: 5695e476953cd3f9a7f77c10f879112b070e8ec65cc171d29cef8ca9.

![SPCOL](https://github.com/cardano-foundation/cardano-token-registry/assets/164620322/e4114606-2b17-4235-b360-aef47c2649ce)

**Comment by VladislavKudrin** [comment]
Done!

**Comment by SPOOLCOLOGNE** [comment]
TKS
