### ISSUE TITLE
Help with registering a token

### ISSUE THREAD

**Issue by JuanTelo** [cardano-foundation/cardano-token-registry#4357]
Hello,

I'm trying to register a token but I'm having difficulties in trying to find out how to pull the signature for each part of the metadata or the public key.

Can this only be done by the person that minted the token? This is a case of a token that had a community takeover, therefore, it's quite difficult to find the initial owner.

**Comment by ScottBlaney** [comment]
yes it must be done by the person who minted the token with the same keys
perhaps you can remint the token with a new policy and airdrop to the existing owners

**Comment by VladislavKudrin** [comment]
Hi @JuanTelo,

@ScottBlaney is right, submission can be done only by the keys' owner.
