### ISSUE TITLE
Error 429 for most requests

### ISSUE THREAD

**Issue by Har01d** [cardano-foundation/cardano-token-registry#4370]
Hey everyone, we're running two block explorers for Cardano ([Blockchair](https://blockchair.com/cardano) and [3xpl](https://3xpl.com/cardano)) and I was wondering what would be the process of white-listing our IP address or getting a key? We're sending not that many requests, but still can't process even the recent blocks.

**Comment by VladislavKudrin** [comment]
Hi @Har01d,

i do not see how it relates to the issue of the token-registry you are displaying recent blocks.
Jurious, what are you using for the cardano info?

**Comment by Godspeed-exe** [comment]
Reached via email 😁 let’s get to the bottom of this 💪✌️
