### ISSUE TITLE
Help with mapping folder and registry

### ISSUE THREAD

**Issue by How-Do-You-Want-To-Do-This** [cardano-foundation/cardano-token-registry#4398]
I have these files after mint but can't figure out how to add them to the mapping folder in a proper format to be able to register the token.
[1_Native_Multi-Sig_Scripts.txt](https://github.com/cardano-foundation/cardano-token-registry/files/14844379/1_Native_Multi-Sig_Scripts.txt)
[witness_set.txt](https://github.com/cardano-foundation/cardano-token-registry/files/14844380/witness_set.txt)
[metadata.txt](https://github.com/cardano-foundation/cardano-token-registry/files/14844381/metadata.txt)

**Comment by VladislavKudrin** [comment]
Hi @How-Do-You-Want-To-Do-This,

you can follow this [guide](https://github.com/cardano-foundation/cardano-token-registry/wiki/How-to-prepare-an-entry-for-the-registry-%28NA-policy-script%29).

**Comment by How-Do-You-Want-To-Do-This** [comment]
> Hi @How-Do-You-Want-To-Do-This,
> 
> you can follow this [guide](https://github.com/cardano-foundation/cardano-token-registry/wiki/How-to-prepare-an-entry-for-the-registry-%28NA-policy-script%29). 

I was referencing that, but when I go to the API it's not allowing me to input query data and if I click download for the API it just gives me a markup script

**Comment by VladislavKudrin** [comment]
Hi @How-Do-You-Want-To-Do-This,

what API

**Comment by How-Do-You-Want-To-Do-This** [comment]
[](https://input-output-hk.github.io/offchain-metadata-tools/api/latest/)
