### ISSUE TITLE
Help adding image and website to token

### ISSUE THREAD

**Issue by LondonPass2024** [cardano-foundation/cardano-token-registry#4412]
Hi there, 

May i get some help registering the image and website for my coin with Policy ID: 167e986f21756eb7b7588c8753500ad5ecfabcadccd176061c67346e

Website: https://www.pepzennegger.xyz

Image as attached: ![Pepzennegger](https://github.com/cardano-foundation/cardano-token-registry/assets/155310722/50fdda44-ad0f-4dd5-b2c0-4c77bc13a2d9)

**Comment by LondonPass2024** [comment]
I forgot, and the Telegram: https://t.me/arnoldpep

**Comment by LondonPass2024** [comment]
I created the following file in the mapping folder but cannot create a pull request; it fails: mappings/167e986f21756eb7b7588c8753500ad5ecfabcadccd176061c67346e504550455a.json

**Comment by LondonPass2024** [comment]
Sorry for all the messages, I think i've done the pull request but not sure if it looks ok: 
https://github.com/cardano-foundation/cardano-token-registry/pull/4413

**Comment by VladislavKudrin** [comment]
Hi @LondonPass2024,

approved!
