### ISSUE TITLE
$ACE token logo is zoomed out

### ISSUE THREAD

**Issue by babyporke** [cardano-foundation/cardano-token-registry#4535]
I’m the founder of $ACE (formerly $BabyPorke)
Policy ID: 7d9aabc78703947e931e28273a96cf7412039fbd2e54a90ffb17239c

could the logo be zoomed in? I’ve attached a better file if that is easier.

thanks
![IMG_6881 2](https://github.com/cardano-foundation/cardano-token-registry/assets/165983358/07a94234-3e12-4220-8edf-1d1326bc13c0)

**Comment by babyporke** [comment]
Issue is I don’t have the keys to the token as I minted it through Cardanotoken.io and he registered it for me. He charged me 350 Ada to change the name and logo and is now asking for 100 more Ada to fix the logo. Any help here? I’d do it myself if I could

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by VladislavKudrin** [comment]
@babyporke,

you should ask cardanotoken.io to give you the policyKeys, after that go to [How to update](https://github.com/cardano-foundation/cardano-token-registry/wiki/How-do-I-update-my-entry-in-the-registry%3F) and try the process (install token-matadata-creator and so on). It is straightforward and should not be afraid of. 

Here is the video that shows how the creation done in details: https://www.youtube.com/watch?v=lZBGTY_luzo&t=589s&ab_channel=%5BMnM%5DMinimumFeeCharityPool-Cardano
From there you can learn how to install token-metadata-creator and how to create new submission.

But until you don't have the keys - we can't do much, unfortunately. 

If you have any questions when you receive the keys - feel free to reopen the issue, until then we will close it.

Good luck!
