### ISSUE TITLE
Can I use this for Testnet

### ISSUE THREAD

**Issue by varianchu** [cardano-foundation/cardano-token-registry#53]
Hi I would like to ask if i can use this for testnet first for testing purposes?

**Comment by admin-cf** [comment]
Hi varianchu

IOG run a registry for testnet here:

https://github.com/input-output-hk/metadata-registry-testnet

**Comment by varianchu** [comment]
Hi, 

Thank you for your reply, im having problems installing offchain-metadata-tools, i think i built it successfully but i cannot use the command token-metadata-creator, can i use this one instead - https://github.com/admin-cf/cardano-metadata-submitter ?

![unnamed](https://user-images.githubusercontent.com/2063765/115504333-5a6a7b80-a2aa-11eb-890f-db5241a6cd99.png)


Thank you

**Comment by admin-cf** [comment]
Hi varianchu,

Have you tried using the precompiled release ?

https://github.com/input-output-hk/offchain-metadata-tools/releases

**Comment by varianchu** [comment]
Hi, i made a pull request in the testnet and received this email. Did i do it correctly? Where can I check if it was successfully uploaded?

![Uploading Screenshot_20210429-010129_Gmail.jpg…]()

**Comment by crptmppt** [comment]
@varianchu  - the testnet repo is managed by IOHK - suggest you try [raising an issue directly on that repo!](https://github.com/input-output-hk/metadata-registry-testnet/issues)

Closing as not relevant to this repo
