### ISSUE TITLE
Merged metadata not showing in Daedalus or Cardano Explorer

### ISSUE THREAD

**Issue by digitalassetnews** [cardano-foundation/cardano-token-registry#61]
Merged metadata is not showing on the explorer or daedalus after > 5 days

https://github.com/cardano-foundation/cardano-token-registry/pull/56

![image](https://user-images.githubusercontent.com/75103895/115926846-9cc4d000-a4d7-11eb-92ec-97012a6949b9.png)

https://explorer.cardano.org/en/transaction?id=605aaf83baa89a862404bd8b9f3d292cde9268948e9fed28bc16c1caefb6eea9

**Comment by digitalassetnews** [comment]
@admin-cf / anyone 

Is this a known issue with all token meta or just isolated to this asset?

**Comment by crptmppt** [comment]
This is being looked into - thank you for your patience!

**Comment by crptmppt** [comment]
The issue should have been resolved, do speak up if still occurring
