### ISSUE TITLE
VOID entries not deleted

### ISSUE THREAD

**Issue by SmaugPool** [cardano-foundation/cardano-token-registry#6502]
According to [How-do-I-delete-my-entry-from-the-registry](https://github.com/cardano-foundation/cardano-token-registry/wiki/How-do-I-delete-my-entry-from-the-registry%3F), `VOID`entries are supposed to be deleted after verification:

> After successful verification we will do the actual deletion of the file.

But several VOID entries are still in the registry without being deleted:
```
$ git grep \"VOID\"
mappings/230ad52f87dde3e38dcf01521dc5c0e62f611cb528917fef2fe6ef8d4d6574617370616365706164.json:        "value": "VOID",
mappings/230ad52f87dde3e38dcf01521dc5c0e62f611cb528917fef2fe6ef8d4d6574617370616365706164.json:        "value": "VOID",
mappings/28193a95061f7f7a64877b6cb8ffea32b30cdb1a73780bfee914032c0014df1052656c61784149.json:        "value": "VOID"
mappings/28193a95061f7f7a64877b6cb8ffea32b30cdb1a73780bfee914032c0014df1052656c61784149.json:        "value": "VOID"
mappings/b437630137ef5cbc469faf303cf9df3a45666105d7b4105b556dd12d5045414348.json:        "value": "VOID",
mappings/b437630137ef5cbc469faf303cf9df3a45666105d7b4105b556dd12d5045414348.json:        "value": "VOID",
mappings/b858a5324b7fdd8e68e2bbac0587b0bf5a68b2bb533c484b41d5b74f564f4944.json:        "value": "VOID",
mappings/b858a5324b7fdd8e68e2bbac0587b0bf5a68b2bb533c484b41d5b74f564f4944.json:        "value": "VOID",
mappings/c5609c4800c05e82c4219ccf14c7fdf5212e11f83dbbb57ac716e98e666c756666.json:        "value": "VOID",
mappings/c5609c4800c05e82c4219ccf14c7fdf5212e11f83dbbb57ac716e98e666c756666.json:        "value": "VOID",
mappings/c5609c4800c05e82c4219ccf14c7fdf5212e11f83dbbb57ac716e98e666c756666.json:        "value": "VOID",
```

As this deletion process and VOID entries are not specified in [CIP26 Off-Chain Metadata Registry](https://github.com/cardano-foundation/cardano-token-registry), these entries are still considered as valid by tools & apps until the files are actually deleted, which cause issues if they are not.

**Comment by SmaugPool** [comment]
Note that [`mappings/bdb1681ea560840c96e05c227d91cc270bd43d75a44f48e3b568cc11566f6964.json`](https://github.com/cardano-foundation/cardano-token-registry/blob/master/mappings/bdb1681ea560840c96e05c227d91cc270bd43d75a44f48e3b568cc11566f6964.json) seems to be an actual valid "Void" token.

So the process kind of conflicts with valid tokens. Maybe in addition to renaming `name` and `description` fields to VOID, the process could require to rename the file to `.deleted`, or move it to a `delete` directory instead of `mappings`, or something else that would avoid conflicts with valid tokens?

**Comment by linconvidal** [comment]
Hey @SmaugPool, thanks for bringing this issue to our attention! We're actively discussing solutions to handle the file deletions as quickly as possible, while also working on process improvements to avoid similar conflicts in the future. We appreciate your patience!
