### ISSUE TITLE
VOID Entries Not Deleted (#6502) – Urgent Attention Needed

### ISSUE THREAD

**Issue by arikbd123** [cardano-foundation/cardano-token-registry#6554]
**Could you kindly check Issue #6502 regarding VOID entries not being deleted from registry?** 
<img width="715" alt="Screenshot 2024-09-06 at 11 08 56 AM" src="https://github.com/user-attachments/assets/cc5b00bd-c95c-4f03-a66b-ab1b3fb30549">
This issue is affecting our project, as people are unable to find our token due to the unresolved VOID entries.

Your immediate attention to this matter would be greatly appreciated.

Thank you for your help.

**Comment by Kartiiyer12** [comment]
The void entries have been deleted. Thank you for raising this.
