### ISSUE TITLE
Issue with mapping in `master`

### ISSUE THREAD

**Issue by codybutz** [cardano-foundation/cardano-token-registry#741]
Hello! I believe that there is a failed mapping in master right now, as you can see from my pull request: https://github.com/cardano-foundation/cardano-token-registry/pull/736 that `6622cfd6be73d6297a6647de9a64f54a5e02d3b60cfb819d2a7c513a436f6f6c4c61756e6368` is causing a failed check - not my policy id of `aade58db4fba94b78ad08a1a240b9c8630fd07421d936dc939c78ab3494e4459`.

**Comment by cleanerm5** [comment]
Hi @codybutz 

I saw that your metadata got merged in the meanwhile.

We had those issues under certain circumstances and adapted the pipeline to prevent this from happening for most scenarios. Although, sometimes it still happens. Workaround is that I close and reopen the PR for it to consider only relevant files until we found out those last edge cases where the diff is calculated in a wrong way.

I'll close this issue for now. Let me know if you need any other assistance in the future.
